apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: CRI_SOCKET
        value: /run/containerd/containerd.sock
    - op: replace
      path: /spec/template/spec/containers/0/volumeMounts/0/mountPath
      value: /run/containerd/containerd.sock
    - op: replace
      path: /spec/template/spec/volumes/0/hostPath/path
      value: /run/containerd/containerd.sock
  target:
    kind: DaemonSet
    name: kubevirt-metrics-exporter
images:
- name: quay.io/openshift-virtualization/kubevirt-metrics-exporter
  newName: localhost/kubevirt-metrics-exporter
  newTag: e2e
