apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ../prometheus-rules
- scc.yaml
- scc-clusterrole.yaml
- scc-clusterrolebinding.yaml
- datasource.yaml
- dashboard.yaml
- dashboard-memory.yaml
- metrics-service.yaml
- metrics-servicemonitor.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/ingress/0/ports/0/port
      value: 8443
  target:
    group: networking.k8s.io
    version: v1
    kind: NetworkPolicy
    name: kubevirt-metrics-exporter-allow-metrics
- patch: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: kubevirt-metrics-exporter
    spec:
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/worker: ""
  target:
    kind: DaemonSet
    name: kubevirt-metrics-exporter
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value: {name: LISTEN_ADDRESS, value: ":8443"}
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value: {name: TLS_CERT_FILE, value: /etc/tls/private/tls.crt}
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value: {name: TLS_KEY_FILE, value: /etc/tls/private/tls.key}
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value: {name: TLS_MIN_VERSION, value: VersionTLS12}
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value: {name: TLS_CIPHER_SUITES, value: "TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-CHACHA20-POLY1305,ECDHE-RSA-CHACHA20-POLY1305"}
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 8443
    - op: replace
      path: /spec/template/spec/containers/0/livenessProbe
      value: {httpGet: {path: /healthz, port: health}, initialDelaySeconds: 10, periodSeconds: 30}
    - op: replace
      path: /spec/template/spec/containers/0/readinessProbe
      value: {httpGet: {path: /healthz, port: health}, initialDelaySeconds: 5, periodSeconds: 10}
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value: {name: metrics-serving-cert, mountPath: /etc/tls/private, readOnly: true}
    - op: add
      path: /spec/template/spec/volumes/-
      value: {name: metrics-serving-cert, secret: {secretName: kubevirt-metrics-exporter-tls}}
  target:
    kind: DaemonSet
    name: kubevirt-metrics-exporter
images:
- name: quay.io/openshift-virtualization/kubevirt-metrics-exporter
  newName: quay.io/openshift-virtualization/kubevirt-metrics-exporter
  newTag: latest
