apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ../podmonitor
images:
- name: quay.io/openshift-virtualization/kubevirt-metrics-exporter
  newName: localhost/kubevirt-metrics-exporter
  newTag: e2e
