apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ../podmonitor
images:
- name: ghcr.io/openshift-virtualization/kubevirt-storage-latency-exporter
  newName: localhost/kubevirt-storage-latency-exporter
  newTag: e2e
