// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type blockBlockHistKey struct {
	_   structs.HostLayout
	Dev uint32
	Op  uint8
	Pad [3]uint8
}

type blockHist struct {
	_     structs.HostLayout
	Slots [26]uint64
}

type blockReqKey struct {
	_      structs.HostLayout
	Dev    uint32
	_      [4]byte
	Sector uint64
}

// loadBlock returns the embedded CollectionSpec for block.
func loadBlock() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BlockBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load block: %w", err)
	}

	return spec, err
}

// loadBlockObjects loads block and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*blockObjects
//	*blockPrograms
//	*blockMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBlockObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBlock()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// blockSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockSpecs struct {
	blockProgramSpecs
	blockMapSpecs
	blockVariableSpecs
}

// blockProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockProgramSpecs struct {
	TracepointBlockBlockRqComplete *ebpf.ProgramSpec `ebpf:"tracepoint__block__block_rq_complete"`
	TracepointBlockBlockRqIssue    *ebpf.ProgramSpec `ebpf:"tracepoint__block__block_rq_issue"`
}

// blockMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockMapSpecs struct {
	BlockHists *ebpf.MapSpec `ebpf:"block_hists"`
	BlockStart *ebpf.MapSpec `ebpf:"block_start"`
}

// blockVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type blockVariableSpecs struct {
}

// blockObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockObjects struct {
	blockPrograms
	blockMaps
	blockVariables
}

func (o *blockObjects) Close() error {
	return _BlockClose(
		&o.blockPrograms,
		&o.blockMaps,
	)
}

// blockMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockMaps struct {
	BlockHists *ebpf.Map `ebpf:"block_hists"`
	BlockStart *ebpf.Map `ebpf:"block_start"`
}

func (m *blockMaps) Close() error {
	return _BlockClose(
		m.BlockHists,
		m.BlockStart,
	)
}

// blockVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockVariables struct {
}

// blockPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBlockObjects or ebpf.CollectionSpec.LoadAndAssign.
type blockPrograms struct {
	TracepointBlockBlockRqComplete *ebpf.Program `ebpf:"tracepoint__block__block_rq_complete"`
	TracepointBlockBlockRqIssue    *ebpf.Program `ebpf:"tracepoint__block__block_rq_issue"`
}

func (p *blockPrograms) Close() error {
	return _BlockClose(
		p.TracepointBlockBlockRqComplete,
		p.TracepointBlockBlockRqIssue,
	)
}

func _BlockClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed block_x86_bpfel.o
var _BlockBytes []byte
