// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type nfsHist struct {
	_     structs.HostLayout
	Slots [26]uint64
}

type nfsNfsHistKey struct {
	_   structs.HostLayout
	Dev uint32
	Op  uint8
	Pad [3]uint8
}

type nfsNfsReqKey struct {
	_      structs.HostLayout
	Dev    uint32
	Count  uint32
	Offset uint64
	Op     uint8
	Pad    [7]uint8
}

// loadNfs returns the embedded CollectionSpec for nfs.
func loadNfs() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NfsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nfs: %w", err)
	}

	return spec, err
}

// loadNfsObjects loads nfs and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nfsObjects
//	*nfsPrograms
//	*nfsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNfsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNfs()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nfsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nfsSpecs struct {
	nfsProgramSpecs
	nfsMapSpecs
	nfsVariableSpecs
}

// nfsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nfsProgramSpecs struct {
	RawTpNfsInitiateRead  *ebpf.ProgramSpec `ebpf:"raw_tp_nfs_initiate_read"`
	RawTpNfsInitiateWrite *ebpf.ProgramSpec `ebpf:"raw_tp_nfs_initiate_write"`
	RawTpNfsReadpageDone  *ebpf.ProgramSpec `ebpf:"raw_tp_nfs_readpage_done"`
	RawTpNfsWritebackDone *ebpf.ProgramSpec `ebpf:"raw_tp_nfs_writeback_done"`
}

// nfsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nfsMapSpecs struct {
	NfsHists *ebpf.MapSpec `ebpf:"nfs_hists"`
	NfsStart *ebpf.MapSpec `ebpf:"nfs_start"`
}

// nfsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nfsVariableSpecs struct {
}

// nfsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNfsObjects or ebpf.CollectionSpec.LoadAndAssign.
type nfsObjects struct {
	nfsPrograms
	nfsMaps
	nfsVariables
}

func (o *nfsObjects) Close() error {
	return _NfsClose(
		&o.nfsPrograms,
		&o.nfsMaps,
	)
}

// nfsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNfsObjects or ebpf.CollectionSpec.LoadAndAssign.
type nfsMaps struct {
	NfsHists *ebpf.Map `ebpf:"nfs_hists"`
	NfsStart *ebpf.Map `ebpf:"nfs_start"`
}

func (m *nfsMaps) Close() error {
	return _NfsClose(
		m.NfsHists,
		m.NfsStart,
	)
}

// nfsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNfsObjects or ebpf.CollectionSpec.LoadAndAssign.
type nfsVariables struct {
}

// nfsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNfsObjects or ebpf.CollectionSpec.LoadAndAssign.
type nfsPrograms struct {
	RawTpNfsInitiateRead  *ebpf.Program `ebpf:"raw_tp_nfs_initiate_read"`
	RawTpNfsInitiateWrite *ebpf.Program `ebpf:"raw_tp_nfs_initiate_write"`
	RawTpNfsReadpageDone  *ebpf.Program `ebpf:"raw_tp_nfs_readpage_done"`
	RawTpNfsWritebackDone *ebpf.Program `ebpf:"raw_tp_nfs_writeback_done"`
}

func (p *nfsPrograms) Close() error {
	return _NfsClose(
		p.RawTpNfsInitiateRead,
		p.RawTpNfsInitiateWrite,
		p.RawTpNfsReadpageDone,
		p.RawTpNfsWritebackDone,
	)
}

func _NfsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nfs_x86_bpfel.o
var _NfsBytes []byte
