// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type nfsKprobeHist struct {
	_     structs.HostLayout
	Slots [26]uint64
}

type nfsKprobeNfsHistKey struct {
	_   structs.HostLayout
	Dev uint32
	Op  uint8
	Pad [3]uint8
}

type nfsKprobeNfsKprobeStartVal struct {
	_   structs.HostLayout
	Ts  uint64
	Dev uint32
	Op  uint8
	Pad [3]uint8
}

// loadNfsKprobe returns the embedded CollectionSpec for nfsKprobe.
func loadNfsKprobe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NfsKprobeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load nfsKprobe: %w", err)
	}

	return spec, err
}

// loadNfsKprobeObjects loads nfsKprobe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*nfsKprobeObjects
//	*nfsKprobePrograms
//	*nfsKprobeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNfsKprobeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNfsKprobe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// nfsKprobeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nfsKprobeSpecs struct {
	nfsKprobeProgramSpecs
	nfsKprobeMapSpecs
	nfsKprobeVariableSpecs
}

// nfsKprobeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nfsKprobeProgramSpecs struct {
	KprobeNfs4FileOpen *ebpf.ProgramSpec `ebpf:"kprobe_nfs4_file_open"`
	KprobeNfsFileOpen  *ebpf.ProgramSpec `ebpf:"kprobe_nfs_file_open"`
	KprobeNfsFileRead  *ebpf.ProgramSpec `ebpf:"kprobe_nfs_file_read"`
	KprobeNfsFileWrite *ebpf.ProgramSpec `ebpf:"kprobe_nfs_file_write"`
	KprobeNfsGetattr   *ebpf.ProgramSpec `ebpf:"kprobe_nfs_getattr"`
	KretprobeNfsVfs    *ebpf.ProgramSpec `ebpf:"kretprobe_nfs_vfs"`
}

// nfsKprobeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nfsKprobeMapSpecs struct {
	NfsKprobeHists *ebpf.MapSpec `ebpf:"nfs_kprobe_hists"`
	NfsKprobeStart *ebpf.MapSpec `ebpf:"nfs_kprobe_start"`
}

// nfsKprobeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type nfsKprobeVariableSpecs struct {
}

// nfsKprobeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNfsKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type nfsKprobeObjects struct {
	nfsKprobePrograms
	nfsKprobeMaps
	nfsKprobeVariables
}

func (o *nfsKprobeObjects) Close() error {
	return _NfsKprobeClose(
		&o.nfsKprobePrograms,
		&o.nfsKprobeMaps,
	)
}

// nfsKprobeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNfsKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type nfsKprobeMaps struct {
	NfsKprobeHists *ebpf.Map `ebpf:"nfs_kprobe_hists"`
	NfsKprobeStart *ebpf.Map `ebpf:"nfs_kprobe_start"`
}

func (m *nfsKprobeMaps) Close() error {
	return _NfsKprobeClose(
		m.NfsKprobeHists,
		m.NfsKprobeStart,
	)
}

// nfsKprobeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNfsKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type nfsKprobeVariables struct {
}

// nfsKprobePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNfsKprobeObjects or ebpf.CollectionSpec.LoadAndAssign.
type nfsKprobePrograms struct {
	KprobeNfs4FileOpen *ebpf.Program `ebpf:"kprobe_nfs4_file_open"`
	KprobeNfsFileOpen  *ebpf.Program `ebpf:"kprobe_nfs_file_open"`
	KprobeNfsFileRead  *ebpf.Program `ebpf:"kprobe_nfs_file_read"`
	KprobeNfsFileWrite *ebpf.Program `ebpf:"kprobe_nfs_file_write"`
	KprobeNfsGetattr   *ebpf.Program `ebpf:"kprobe_nfs_getattr"`
	KretprobeNfsVfs    *ebpf.Program `ebpf:"kretprobe_nfs_vfs"`
}

func (p *nfsKprobePrograms) Close() error {
	return _NfsKprobeClose(
		p.KprobeNfs4FileOpen,
		p.KprobeNfsFileOpen,
		p.KprobeNfsFileRead,
		p.KprobeNfsFileWrite,
		p.KprobeNfsGetattr,
		p.KretprobeNfsVfs,
	)
}

func _NfsKprobeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nfskprobe_x86_bpfel.o
var _NfsKprobeBytes []byte
